// ═══ VML DECK ENGINE v10.5 ═══

var C={black:'191919',white:'F5F5F5',dkGray:'363732',mdGray:'53544A',gray:'8B8C81',ltGray:'C2C4B8',accent:AH,accentLight:AL,accentDark:AD};
var FONT={head:'Snowflake Sans Medium',body:'Snowflake Sans Book'};
var VP={w:{vB:'0 0 1770 612',p:['M1151.56,50l93.46,512h-148.31l-37.13-294.56-81.12,294.56h-133.1l-81.12-294.56-37.13,294.56h-148.3l93.46-512h156.9l82.74,300.84,82.75-300.84h156.9ZM445.36,50l-120.74,345.5L203.89,50H50.27l193.37,512h161.98L598.98,50h-153.62ZM1460.2,430.93V50h-141.89v512h351.93l49.5-131.07h-259.54Z']},i:{vB:'0 0 512 512',p:['M512,463.67v48.33h-48.33l-207.67-207.67L48.33,512H0v-48.33s207.67-207.67,207.67-207.67L0,48.33V0s48.33,0,48.33,0l207.67,207.67L463.67,0h48.33v48.33l-207.67,207.67,207.67,207.67ZM306.77,0l-50.77,50.77L205.23,0h-87.33l138.09,138.09L394.09,0h-87.33ZM394.09,512l-138.09-138.09-138.09,138.09h87.33l50.77-50.77,50.77,50.77h87.33ZM512,306.77l-50.77-50.77,50.77-50.77v-87.33l-138.09,138.09,138.09,138.09v-87.33ZM0,394.09l138.09-138.09L0,117.91v87.33l50.77,50.77L0,306.77v87.33Z']}};
function rl(p,w,h,f){try{var c=document.createElement('canvas');c.width=w*2;c.height=h*2;var x=c.getContext('2d');var v=p.vB.split(/[\s,]+/).map(Number);var s=Math.min(w*2/v[2],h*2/v[3]);x.translate((w*2-v[2]*s)/2,(h*2-v[3]*s)/2);x.scale(s,s);x.fillStyle=f;p.p.forEach(function(d){x.fill(new Path2D(d));});return c.toDataURL('image/png');}catch(e){return null;}}
var L={wW:rl(VP.w,150,52,'#F5F5F5'),bW:rl(VP.w,150,52,'#191919'),wI:rl(VP.i,60,60,'#F5F5F5'),bI:rl(VP.i,60,60,'#191919')};
var PPI=80;var FW=1.15;var FH=1.08;
function px(v){return Math.round(v*PPI);}
function rc(k,dk){if(C[k])return C[k];switch(k){case 'title':return dk?C.white:C.black;case 'body':return dk?C.ltGray:C.mdGray;case 'sub':return dk?C.accentLight:C.mdGray;case 'muted':return C.gray;case 'cardBg':return dk?C.dkGray:'FFFFFF';case 'ok':return '28A745';case 'warn':return 'E67E00';case 'bad':return 'C12638';default:return k;}}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML.replace(/\n/g,'<br>');}
function findImg(container){if(!container)return null;var imgs=container.querySelectorAll('img');for(var k=0;k<imgs.length;k++){if(imgs[k].src&&imgs[k].src!==''&&imgs[k].src!==window.location.href&&imgs[k].src.indexOf('data:image/svg')===-1)return imgs[k];}return null;}
function captureImage(imgElement,tw,th){return new Promise(function(resolve){var getCrop=function(nw,nh){var tr=tw/th,ir=nw/nh,sx=0,sy=0,sw=nw,sh=nh;if(ir>tr){sw=nh*tr;sx=(nw-sw)/2;}else{sh=nw/tr;sy=(nh-sh)/2;}var cw=Math.min(Math.round(tw*96),1200),ch=Math.min(Math.round(th*96),800);return{sx:sx,sy:sy,sw:sw,sh:sh,cw:cw,ch:ch};};try{var crop=getCrop(imgElement.naturalWidth||800,imgElement.naturalHeight||600);var canvas=document.createElement('canvas');canvas.width=crop.cw;canvas.height=crop.ch;canvas.getContext('2d').drawImage(imgElement,crop.sx,crop.sy,crop.sw,crop.sh,0,0,crop.cw,crop.ch);resolve(canvas.toDataURL('image/jpeg',0.85));}catch(e){try{fetch(imgElement.src).then(function(r){return r.blob();}).then(function(blob){var img=new Image();img.addEventListener('load',function(){var crop=getCrop(img.width||800,img.height||600);var c=document.createElement('canvas');c.width=crop.cw;c.height=crop.ch;c.getContext('2d').drawImage(img,crop.sx,crop.sy,crop.sw,crop.sh,0,0,crop.cw,crop.ch);resolve(c.toDataURL('image/jpeg',0.75));});img.src=URL.createObjectURL(blob);}).catch(function(){resolve(null);});}catch(e2){resolve(null);}}});}

// ═══ CLIENT BRANDING ═══
var CL_WHITE=null;var CL_BLACK=null;var CLIENT_H_PX=16;var CLIENT_AR=2;
function recolorSVG(svgText,color){var s=svgText;
s=s.replace(/fill="(?!none)[^"]*"/g,'fill="'+color+'"');
s=s.replace(/fill:\s*(?!none)[^;"']*/g,'fill:'+color);
s=s.replace(/<style[^>]*>[\s\S]*?<\/style>/g,function(m){return m.replace(/fill:\s*[^;}"']*/g,'fill:'+color);});
if(svgText.indexOf('fill')===-1)s=s.replace('<svg','<svg fill="'+color+'"');return s;}
function renderSVGToImage(svgText,color,maxH,callback){var colored=recolorSVG(svgText,color);var parser=new DOMParser();var doc=parser.parseFromString(colored,'image/svg+xml');var svgEl=doc.querySelector('svg');var vb=svgEl?svgEl.getAttribute('viewBox'):null;var sw_=svgEl?parseFloat(svgEl.getAttribute('width')||0):0;var sh_=svgEl?parseFloat(svgEl.getAttribute('height')||0):0;var ar=2;if(vb){var p=vb.split(/[\s,]+/).map(Number);ar=p[2]/p[3];}else if(sw_&&sh_)ar=sw_/sh_;var rH=maxH*3,rW=Math.round(rH*ar);var finalSVG=colored.replace(/<svg([^>]*)>/,function(m,a){var n=a.replace(/\s*width="[^"]*"/g,'').replace(/\s*height="[^"]*"/g,'');return'<svg'+n+' width="'+rW+'" height="'+rH+'">';});var blob=new Blob([finalSVG],{type:'image/svg+xml;charset=utf-8'});var url=URL.createObjectURL(blob);var img=new Image();img.onload=function(){var canvas=document.createElement('canvas');canvas.width=rW;canvas.height=rH;var ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,rW,rH);URL.revokeObjectURL(url);var data=ctx.getImageData(0,0,rW,rH).data;var t=rH,le=rW,b=0,r=0;for(var y=0;y<rH;y++)for(var x=0;x<rW;x++){if(data[(y*rW+x)*4+3]>10){if(x<le)le=x;if(x>r)r=x;if(y<t)t=y;if(y>b)b=y;}}if(r<=le||b<=t){callback(null,1);return;}var pad=Math.round(Math.min(r-le,b-t)*0.03);le=Math.max(0,le-pad);t=Math.max(0,t-pad);r=Math.min(rW-1,r+pad);b=Math.min(rH-1,b+pad);var cw=r-le+1,ch=b-t+1;var cr=document.createElement('canvas');cr.width=cw;cr.height=ch;cr.getContext('2d').drawImage(canvas,le,t,cw,ch,0,0,cw,ch);callback(cr.toDataURL('image/png'),cw/ch);};img.onerror=function(){URL.revokeObjectURL(url);callback(null,1);};img.src=url;}
function hexToRgb(h){h=h.replace('#','');return{r:parseInt(h.substr(0,2),16),g:parseInt(h.substr(2,2),16),b:parseInt(h.substr(4,2),16)};}
function rgbToHex(r,g,b){return'#'+[r,g,b].map(function(v){var x=Math.round(Math.max(0,Math.min(255,v))).toString(16);return x.length===1?'0'+x:x;}).join('');}
function lightenHex(h,p){var c=hexToRgb(h);return rgbToHex(c.r+(255-c.r)*p,c.g+(255-c.g)*p,c.b+(255-c.b)*p);}

// ═══ RENDER ═══
function renderAll(){
var w=document.getElementById('sw'),h='';
var noVml=(typeof NO_VML!=='undefined'&&NO_VML);
D.forEach(function(s,i){
var dk=s.dark;
var numColor=dk?'#F5F5F5':'#191919';
h+='<div class="sf '+(dk?'dk':'lt')+'" style="display:'+(i===0?'block':'none')+';">';
h+='<div class="ab" style="background:#'+C.accent+';"></div>';
h+='<div class="sn" style="color:'+numColor+';font-weight:600;">'+s.num+'</div>';
if(!noVml){h+='<img class="li" src="'+(dk?L.wI:L.bI)+'">';}
s.els.forEach(function(el){
if(el.type==='t'){h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;width:'+px(el.w)+'px;'+(el.h?'height:'+px(el.h)+'px;':'')+'font-size:'+el.size+'px;color:#'+rc(el.color,dk)+';font-weight:'+(el.font==='H'?'500':'400')+';line-height:1.4;">'+esc(el.text)+'</div>';}
else if(el.type==='s'){var bdr=el.border?'border:'+(el.bw||1)+'px solid #'+rc(el.border,dk)+';':'';h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;width:'+px(el.w)+'px;height:'+px(el.h)+'px;background:#'+rc(el.fill,dk)+';'+bdr+'"></div>';}
else if(el.type==='o'){h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;width:'+px(el.w)+'px;height:'+px(el.h||el.w)+'px;background:#'+rc(el.fill,dk)+';border-radius:50%;"></div>';}
else if(el.type==='i'){h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;width:'+px(el.w)+'px;height:'+px(el.h||el.w)+'px;font-size:'+px(el.w*.7)+'px;display:flex;align-items:center;justify-content:center;line-height:1;">'+el.icon+'</div>';}
else if(el.type==='d'){h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;width:'+px(el.w)+'px;height:'+(el.h?px(el.h):2)+'px;background:#'+rc(el.color||'accent',dk)+';"></div>';}
else if(el.type==='p'){var bg=rc(el.fill||'accent',dk),tc=rc(el.color||'black',dk);h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;padding:4px 14px;background:#'+bg+';color:#'+tc+';font-size:'+(el.size||10)+'px;font-weight:500;white-space:nowrap;">'+esc(el.text)+'</div>';}
else if(el.type==='b'){h+='<div style="position:absolute;left:'+px(el.x)+'px;top:'+px(el.y)+'px;width:'+px(el.w)+'px;height:'+px(el.h)+'px;background:#'+rc(el.fill||'accent',dk)+';"></div>';}
});
h+='<div style="position:absolute;left:29px;bottom:12px;display:flex;align-items:center;gap:8px;">';
if(!noVml){h+='<img src="'+(dk?L.wW:L.bW)+'" style="height:17px;">';}
var cl=dk?CL_WHITE:CL_BLACK;
if(cl){
if(!noVml){h+='<div style="width:4px;height:4px;background:#8B8C81;flex-shrink:0;"></div>';}
h+='<img src="'+cl+'" style="height:'+CLIENT_H_PX+'px;object-fit:contain;">';}
h+='</div>';
if(s.footer)h+='<div style="position:absolute;right:20px;bottom:16px;font-size:7px;color:#'+C.gray+';">'+esc(s.footer)+'</div>';
h+='</div>';
});
w.innerHTML=h;
}
function refreshSlides(){var frames=document.querySelectorAll('.sf');frames.forEach(function(f,idx){f.style.display=idx===cur?'block':'none';});document.getElementById('nc').textContent=(cur+1)+' / '+D.length;document.getElementById('hc').textContent='SLIDE '+(cur+1)+' OF '+D.length;}
function placeImages(){D.forEach(function(s,i){s.els.forEach(function(el){if(el.type==='img'){var container=document.getElementById(el.ref);if(container){var frames=document.querySelectorAll('.sf');if(frames[i]){container.style.position='absolute';container.style.left=px(el.x)+'px';container.style.top=px(el.y)+'px';container.style.width=px(el.w)+'px';container.style.height=px(el.h)+'px';container.style.display='block';frames[i].appendChild(container);}}}});});}
function aL(sl,dk,pptx){var noVml=(typeof NO_VML!=='undefined'&&NO_VML);var wm=dk?L.wW:L.bW,ic=dk?L.wI:L.bI;var VML_H_IN=0.21,VML_W_IN=0.68,CLIENT_H_IN=CLIENT_H_PX/80,CLIENT_W_IN=CLIENT_H_IN*CLIENT_AR,DOT_SIZE=0.04;if(!noVml&&ic)sl.addImage({data:ic,x:.29,y:.21,w:.21,h:.21,sizing:{type:'contain',w:.21,h:.21}});if(!noVml&&wm)sl.addImage({data:wm,x:.29,y:7.0,w:VML_W_IN,h:VML_H_IN,sizing:{type:'contain',w:VML_W_IN,h:VML_H_IN}});var cl=dk?CL_WHITE:CL_BLACK;if(cl){if(!noVml){var dotX=.29+VML_W_IN+0.08,dotY=7.0+(VML_H_IN-DOT_SIZE)/2;sl.addShape(pptx.shapes.RECTANGLE,{x:dotX,y:dotY,w:DOT_SIZE,h:DOT_SIZE,fill:{color:C.gray}});var clX=dotX+DOT_SIZE+0.08,clY=7.0+(VML_H_IN-CLIENT_H_IN)/2;sl.addImage({data:cl,x:clX,y:clY,w:CLIENT_W_IN,h:CLIENT_H_IN});}else{sl.addImage({data:cl,x:.29,y:7.0+(VML_H_IN-CLIENT_H_IN)/2,w:CLIENT_W_IN,h:CLIENT_H_IN});}}}
function ms(pptx,s){var sl=pptx.addSlide(),dk=s.dark;sl.background={color:dk?C.black:C.white};aL(sl,dk,pptx);sl.addShape(pptx.shapes.RECTANGLE,{x:.29,y:.55,w:12.75,h:.02,fill:{color:C.accent}});if(s.num)sl.addText(s.num,{x:12.3,y:.31,w:.75,h:.2,fontSize:10,fontFace:FONT.head,color:dk?C.white:C.black,align:'right',bold:true,autoFit:true});if(s.footer)sl.addText(s.footer,{x:8,y:7.0,w:5,h:.25,fontSize:7,fontFace:FONT.body,color:dk?C.gray:C.mdGray,align:'right',autoFit:true});return sl;}
async function bs(pptx,s,slideIdx){var sl=ms(pptx,s),dk=s.dark;for(var j=0;j<s.els.length;j++){var el=s.els[j];if(el.type==='t'){sl.addText(el.text,{x:el.x,y:el.y,w:el.w*FW,h:(el.h||.3)*FH,fontFace:el.font==='H'?FONT.head:FONT.body,fontSize:el.size,color:rc(el.color,dk),valign:'top',autoFit:true});}else if(el.type==='s'){var opts={x:el.x,y:el.y,w:el.w,h:el.h,fill:{color:rc(el.fill,dk)}};if(el.border)opts.line={color:rc(el.border,dk),width:el.bw||1};sl.addShape(pptx.shapes.RECTANGLE,opts);}else if(el.type==='o'){sl.addShape(pptx.shapes.OVAL,{x:el.x,y:el.y,w:el.w,h:el.h||el.w,fill:{color:rc(el.fill,dk)}});}else if(el.type==='i'){sl.addText(el.icon,{x:el.x,y:el.y,w:el.w*FW,h:(el.h||el.w)*FH,fontSize:el.size||Math.round(el.w*40),align:'center',valign:'middle',autoFit:true});}else if(el.type==='d'){sl.addShape(pptx.shapes.RECTANGLE,{x:el.x,y:el.y,w:el.w,h:el.h||0.02,fill:{color:rc(el.color||'accent',dk)}});}else if(el.type==='p'){sl.addText(el.text,{x:el.x,y:el.y,w:(el.w||1.5)*FW,h:(el.h||.3)*FH,fontSize:el.size||10,fontFace:FONT.head,color:rc(el.color||'black',dk),fill:{color:rc(el.fill||'accent',dk)},align:'center',valign:'middle',autoFit:true});}else if(el.type==='b'){sl.addShape(pptx.shapes.RECTANGLE,{x:el.x,y:el.y,w:el.w,h:el.h,fill:{color:rc(el.fill||'accent',dk)}});}else if(el.type==='img'){var container=document.getElementById(el.ref);var genImg=findImg(container);if(genImg){try{var imgData=await captureImage(genImg,el.w,el.h);if(imgData){sl.addImage({data:imgData,x:el.x,y:el.y,w:el.w,h:el.h});}}catch(e){}}}}}
async function dlP(){var btn=document.getElementById('dlBtn'),st=document.getElementById('st');btn.disabled=true;btn.textContent='Compiling...';try{if(typeof PptxGenJS==='undefined'){st.textContent='Loading library...';await new Promise(function(res,rej){var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs/dist/pptxgen.bundle.js';s.onload=res;s.onerror=function(){rej(new Error('PptxGenJS failed'));};document.head.appendChild(s);});}var allFrames=document.querySelectorAll('.sf');allFrames.forEach(function(f){f.style.display='block';});st.textContent='Preparing images...';await new Promise(function(r){setTimeout(r,1000);});var pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.title=document.getElementById('deckTitle').innerText;pptx.subject='VML v'+(typeof PV!=='undefined'?PV:'');pptx.company='WPP - VML';pptx.theme={headFontFace:'Snowflake Sans Medium',bodyFontFace:'Snowflake Sans Book'};for(var i=0;i<D.length;i++){st.textContent='Compiling slide '+(i+1)+' of '+D.length+'...';await new Promise(function(r){requestAnimationFrame(r);});await bs(pptx,D[i],i);}st.textContent='Packaging...';await new Promise(function(r){requestAnimationFrame(r);});var t=document.getElementById('deckTitle').innerText.replace(/[^a-zA-Z0-9]/g,'_');await pptx.writeFile({fileName:'VML_'+t+'_'+D.length+'slides.pptx'});allFrames.forEach(function(f,idx){f.style.display=idx===cur?'block':'none';});st.textContent='\u2705 Download complete!';}catch(e){st.textContent='Error: '+e.message;var af=document.querySelectorAll('.sf');af.forEach(function(f,idx){f.style.display=idx===cur?'block':'none';});}btn.disabled=false;btn.textContent='\u2B07 DOWNLOAD PPTX';}
var cur=0;
function show(i){var f=document.querySelectorAll('.sf');if(i<0||i>=f.length)return;f[cur].style.display='none';cur=i;f[cur].style.display='block';document.getElementById('nc').textContent=(cur+1)+' / '+D.length;document.getElementById('hc').textContent='SLIDE '+(cur+1)+' OF '+D.length;}
function scl(){var vp=document.getElementById('vp'),wr=document.getElementById('sw');var s=Math.min((vp.clientWidth-32)/1066,(vp.clientHeight-8)/600,1);wr.style.transform='scale('+s+')';wr.style.transformOrigin='top center';}

// ═══ INIT — default mode (wires events on existing DOM) ═══
function init(){
renderAll();scl();refreshSlides();setTimeout(placeImages,500);
document.getElementById('pBtn').addEventListener('click',function(){show(cur-1);});
document.getElementById('nBtn').addEventListener('click',function(){show(cur+1);});
document.getElementById('dlBtn').addEventListener('click',dlP);
window.addEventListener('resize',scl);
document.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')show(cur-1);if(e.key==='ArrowRight')show(cur+1);});
if(document.getElementById('uploadBtn')){
document.getElementById('uploadBtn').addEventListener('click',function(){document.getElementById('fileInput').click();});
document.getElementById('fileInput').addEventListener('change',function(e){if(!e.target.files[0])return;var reader=new FileReader();reader.addEventListener('load',function(ev){var svgText=ev.target.result;document.getElementById('uploadBtn').classList.add('loaded');document.getElementById('uploadBtn').textContent='\u2705 '+e.target.files[0].name;var rmBtn=document.getElementById('removeBtn');if(rmBtn)rmBtn.style.display='inline-block';var done=0;renderSVGToImage(svgText,'#F5F5F5',60,function(d,ar){CL_WHITE=d;if(ar)CLIENT_AR=ar;done++;if(done===2){renderAll();refreshSlides();}});renderSVGToImage(svgText,'#191919',60,function(d,ar){CL_BLACK=d;if(ar)CLIENT_AR=ar;done++;if(done===2){renderAll();refreshSlides();}});});reader.readAsText(e.target.files[0]);});
var rmBtn=document.getElementById('removeBtn');if(rmBtn){rmBtn.addEventListener('click',function(){CL_WHITE=null;CL_BLACK=null;CLIENT_AR=2;document.getElementById('uploadBtn').classList.remove('loaded');document.getElementById('uploadBtn').textContent='\uD83D\uDCD0 Upload Client/Partner Logo';this.style.display='none';document.getElementById('fileInput').value='';renderAll();refreshSlides();});}
document.getElementById('colorPick').addEventListener('input',function(e){var hex=e.target.value.replace('#','').toUpperCase();C.accent=hex;AH=hex;C.accentLight=lightenHex('#'+hex,0.35).replace('#','').toUpperCase();AL=C.accentLight;document.getElementById('hexVal').textContent='#'+hex;document.getElementById('dlBtn').style.background='#'+hex;renderAll();refreshSlides();});
document.getElementById('sizeSlider').addEventListener('input',function(e){CLIENT_H_PX=parseInt(e.target.value);document.getElementById('szVal').textContent=CLIENT_H_PX;renderAll();refreshSlides();});
}
}

// ═══ INIT IMG — image mode (DOM manipulation, no re-render) ═══
function initImg(){
document.querySelectorAll('.li').forEach(function(el){el.src=el.closest('.sf').classList.contains('dk')?L.wI:L.bI;});
document.querySelectorAll('.lw').forEach(function(el){el.src=el.closest('.sf').classList.contains('dk')?L.wW:L.bW;});
scl();setTimeout(placeImages,500);
document.getElementById('pBtn').addEventListener('click',function(){show(cur-1);});
document.getElementById('nBtn').addEventListener('click',function(){show(cur+1);});
document.getElementById('dlBtn').addEventListener('click',dlP);
window.addEventListener('resize',scl);
document.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')show(cur-1);if(e.key==='ArrowRight')show(cur+1);});
var prevAcc=AH,prevAccLt=AL;
if(document.getElementById('uploadBtn')){
document.getElementById('uploadBtn').addEventListener('click',function(){document.getElementById('fileInput').click();});
document.getElementById('fileInput').addEventListener('change',function(e){if(!e.target.files[0])return;var reader=new FileReader();reader.addEventListener('load',function(ev){var svgText=ev.target.result;document.getElementById('uploadBtn').classList.add('loaded');document.getElementById('uploadBtn').textContent='\u2705 '+e.target.files[0].name;var rmBtn=document.getElementById('removeBtn');if(rmBtn)rmBtn.style.display='inline-block';var done=0;function injectLogos(){document.querySelectorAll('.sf').forEach(function(slide){var dk=slide.classList.contains('dk');var footers=slide.querySelectorAll('[style*="bottom:12px"]');var footer=footers.length?footers[footers.length-1]:null;if(!footer)return;var cl=dk?CL_WHITE:CL_BLACK;if(cl){var existing=footer.querySelector('.f-cl');if(existing)existing.remove();var dot=footer.querySelector('.f-dot');if(dot)dot.remove();var dotEl=document.createElement('div');dotEl.className='f-dot';dotEl.style.cssText='width:4px;height:4px;background:#8B8C81;flex-shrink:0;';footer.appendChild(dotEl);var img=document.createElement('img');img.className='f-cl';img.src=cl;img.style.cssText='height:'+CLIENT_H_PX+'px;object-fit:contain;';footer.appendChild(img);}});}
renderSVGToImage(svgText,'#F5F5F5',60,function(d,ar){CL_WHITE=d;if(ar)CLIENT_AR=ar;done++;if(done===2)injectLogos();});renderSVGToImage(svgText,'#191919',60,function(d,ar){CL_BLACK=d;if(ar)CLIENT_AR=ar;done++;if(done===2)injectLogos();});});reader.readAsText(e.target.files[0]);});
var rmBtn=document.getElementById('removeBtn');if(rmBtn){rmBtn.addEventListener('click',function(){CL_WHITE=null;CL_BLACK=null;CLIENT_AR=2;document.getElementById('uploadBtn').classList.remove('loaded');document.getElementById('uploadBtn').textContent='\uD83D\uDCD0 Upload Client/Partner Logo';this.style.display='none';document.getElementById('fileInput').value='';document.querySelectorAll('.f-cl').forEach(function(el){el.remove();});document.querySelectorAll('.f-dot').forEach(function(el){el.remove();});});}
document.getElementById('colorPick').addEventListener('input',function(e){var hex=e.target.value.replace('#','').toUpperCase();var oldA='#'+prevAcc;var oldAL='#'+prevAccLt;C.accent=hex;AH=hex;C.accentLight=lightenHex('#'+hex,0.35).replace('#','').toUpperCase();AL=C.accentLight;var newA='#'+hex;var newAL='#'+C.accentLight;document.getElementById('hexVal').textContent='#'+hex;document.getElementById('dlBtn').style.background='#'+hex;document.querySelectorAll('.ab').forEach(function(el){el.style.background='#'+hex;});document.querySelectorAll('.sf [style]').forEach(function(el){var s=el.getAttribute('style');if(s&&(s.toLowerCase().indexOf(oldA.toLowerCase())!==-1||s.toLowerCase().indexOf(oldAL.toLowerCase())!==-1)){s=s.replace(new RegExp(oldA,'gi'),newA);s=s.replace(new RegExp(oldAL,'gi'),newAL);el.setAttribute('style',s);}});prevAcc=hex;prevAccLt=C.accentLight;});
document.getElementById('sizeSlider').addEventListener('input',function(e){CLIENT_H_PX=parseInt(e.target.value);document.getElementById('szVal').textContent=CLIENT_H_PX;document.querySelectorAll('.f-cl').forEach(function(img){img.style.height=CLIENT_H_PX+'px';});});
}
}
